#!/bin/sh
#
# Copy terminal logs to persistent storage on shutdown
#

LOG_DIR='/var/log'
LOG_TARBALL="/root/logs.tar.gz"

start() {
	echo "Unpacking logs..."
	# have to do this in two steps since busybox tar doesnt support gzip
	gunzip -dc $LOG_TARBALL | tar xf - -C $LOG_DIR
	echo "Done"
}

stop() {
	echo "Saving logs..."
	cd $LOG_DIR
	tar cf - *.log | gzip -9 > $LOG_TARBALL
	echo "Done"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
