#!/bin/sh
#
# Copy terminal logs to persistent storage on shutdown
#

LOG_DIR='/var/log'

start() {
	echo "Unpacking logs..."
	# have to do this in two steps since busybox tar doesnt support gzip
	gunzip -dc /root/logs.tar.gz | tar xf - -C $LOG_DIR
	echo "Done"
}

stop() {
	echo "Saving logs..."
	cd $LOG_DIR
	tar cf - *.log | gzip -9 > /root/logs.tar.gz
	echo "Done"
}

case "$1" in
  start)
	# nothing to do
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {stop}"
	exit 1
esac

exit $?
