#!/bin/sh
#
# Copy terminal logs to persistent storage on shutdown
#

LOG_DIR='/var/log'

stop() {
	echo "Saving terminal logs..."
	test -d "$SAVE_DIR" && rm -rf "$SAVE_DIR"
	cd $LOG_DIR
	tar cf - *.log | gzip -9 > /root/logs.tar.gz
	echo "Done"
}

case "$1" in
  start)
	# nothing to do
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {stop}"
	exit 1
esac

exit $?
