#!/bin/sh
#
# Copy terminal logs to persistent storage on shutdown
#

LOG_DIR='/var/log'
SAVE_DIR='/root/saved_logs'

stop() {
	echo "Saving terminal logs..."
	test -d "$SAVE_DIR" && rm -rf "$SAVE_DIR"
	mkdir -p "$SAVE_DIR"
	cp -v $LOG_DIR/terminal.*.log "$SAVE_DIR"
	echo "Done"
}

case "$1" in
  start)
	# nothing to do
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {stop}"
	exit 1
esac

exit $?
