#!/bin/sh
#
# swupdate        Starts swupdate with "selection" based on /proc/cmdline.
#

start() {
	echo "Parsing /proc/cmdline"
	COPY_ID="$(/bin/grep -o 'copy=[[:graph:]]*' /proc/cmdline | cut -d'=' -f2)"

	echo "Result:"
	echo " - $COPY_ID"
	SELECTION="tsat3500,$COPY_ID"

	printf "Starting swupdate: "
	/usr/bin/swupdate --select "$SELECTION" --key /usr/local/share/public.pem >>/var/log/swupdate-server.log 2>&1 &
	touch /var/lock/swupdate
	echo "OK"
}
stop() {
	printf "Stopping swupdate: "
	killall swupdate
	rm -f /var/lock/swupdate
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

